# .github/workflows/release.yml

name: release

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Bump new version
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: ruby
          package-name: "ibrain-auth"
          bump-minor-pre-major: true
          version-file: "lib/ibrain/auth/version.rb"
      - name: Checkout code if release was created
        uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}
      - name: Setup ruby if a release was created
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
        if: ${{ steps.release.outputs.release_created }}
      - name: Install bundle
        run: bundle install
        if: ${{ steps.release.outputs.release_created }}
      - name: Publish gem
        id: step_publish_gem
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${{ secrets.RUBYGEMS_AUTH_TOKEN }}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
        if: ${{ steps.release.outputs.release_created }}
